use sakila;

-- 1 List the number of films per category.

SELECT c.name as category_name,COUNT(fc.film_id) as num_of_films 
FROM category c
JOIN film_category fc ON c.category_id=fc.category_id
GROUP BY category_name;

-- 2 Retrieve the store ID, city, and country for each store.

SELECT s.store_id,c.city as city,co.country as country
FROM store s
JOIN address a ON a.address_id=s.address_id
JOIN city c ON c.city_id=a.city_id
JOIN country co ON co.country_id=c.country_id;

-- 3 Calculate the total revenue generated by each store in dollars.

SELECT s.store_id,SUM(p.amount) as total_revenue
FROM store s
JOIN staff st ON s.store_id=st.store_id
JOIN payment p ON p.staff_id=st.staff_id
GROUP BY s.store_id;

-- 4 Determine the average running time of films for each category.

SELECT AVG(f.length) as avg_running_time,c.name
FROM film f
JOIN film_category fc ON f.film_id=fc.film_id
JOIN category c ON c.category_id=fc.category_id
GROUP BY name;

-- Bonus 
-- 5.Identify the film categories with the longest average running time.

SELECT AVG(f.length) as avg_running_time,c.name
FROM film f
JOIN film_category fc ON f.film_id=fc.film_id
JOIN category c ON c.category_id=fc.category_id
GROUP BY name
ORDER BY avg_running_time DESC
LIMIT 5;

-- 6
-- Display the top 10 most frequently rented movies in descending order.

Select * from rental;
-- I assume which movies has been rented the most or frewquently
SELECT f.title as movie_name,COUNT(r.rental_id) as most_rented_movies
FROM rental r
JOIN inventory i on r.inventory_id=i.inventory_id
JOIN film f ON i.film_id=f.film_id
GROUP BY movie_name
ORDER BY most_rented_movies DESC
LIMIT 10;


-- 7 Determine if "Academy Dinosaur" can be rented from Store 1.

SELECT f.title as film,s.store_id
FROM inventory i
JOIN film f ON i.film_id =f.film_id
JOIN store s ON i.store_id=s.store_id
WHERE 
f.title= 'Academy Dinosaur' AND s.store_id=1;

-- 8

SELECT
    f.title AS film_title,
    CASE
        WHEN i.film_id IS NOT NULL THEN 'Available'
        ELSE 'NOT Available'
    END AS availability_status
FROM
    film f
LEFT JOIN
    inventory i ON f.film_id = i.film_id
GROUP BY
    f.title, i.inventory_id;
